export const DUALITY_STARTED = 'DUALITY_STARTED';
export const EVENT_STARTED = 'EVENT_STARTED';
export const EVENT_MESSAGE_READY = 'EVENT_MESSAGE_READY';
export const QUEST_STARTED = 'QUEST_STARTED';
export const QUEST_READY = 'QUEST_READY';
export const QUEST_COMPLETED = 'QUEST_COMPLETED';
export const EVENT_COMPLETED = 'EVENT_COMPLETED';
export const DUALITY_COMPLETED = 'DUALITY_COMPLETED';
export const DUALITY_STAGE_STARTED = 'DUALITY_STAGE_STARTED';
export const DETECTION_SEARCH = 'DETECTION_SEARCH';
export const DETECTION_DONE_EVENT = 'DETECTION_DONE';
export const DETECTION_STOPPED = 'DETECTION_STOPPED';
export const BUTTON_STATE_UPDATED = 'BUTTON_STATE_UPDATED';
export const BUTTON_VISIBILITY_UPDATED = 'BUTTON_VISIBILITY_UPDATED';
export const EFFECT_UPDATE_REQUESTED = 'EFFECT_UPDATE_REQUESTED';
export const EFFECT_STYLE_UPDATED = 'EFFECT_STYLE_UPDATED';
export const EFFECT_DEFAULTS_SAVED = 'EFFECT_DEFAULTS_SAVED';
// Emitted when dialog widget has finished initialization
export const DIALOG_WIDGET_READY = 'DIALOG_WIDGET_READY';
// Clears dialog messages when switching ghosts
export const DIALOG_CLEAR = 'DIALOG_CLEAR';
// View rendering requests emitted by application services
export const VIEW_RENDER_REQUESTED = 'VIEW_RENDER_REQUESTED';
export const VIEW_CAMERA_RENDER_REQUESTED = 'VIEW_CAMERA_RENDER_REQUESTED';
// Messenger content prepared by application services
export const MESSENGER_POSTS_READY = 'MESSENGER_POSTS_READY';
// Registration screen hydration lifecycle
export const REGISTRATION_NAME_CHANGED = 'REGISTRATION_NAME_CHANGED';
// Geo status updates routed through the presenter
export const GEO_STATUS_UPDATED = 'GEO_STATUS_UPDATED';
// Camera preview lifecycle events handled by the presenter
export const CAMERA_PREVIEW_READY = 'CAMERA_PREVIEW_READY';
export const CAMERA_PREVIEW_CLEARED = 'CAMERA_PREVIEW_CLEARED';
// Global reset orchestration events
export const APP_RESET_REQUESTED = 'APP_RESET_REQUESTED';
export const APP_RESET_COMPLETED = 'APP_RESET_COMPLETED';
// Profile import/export flow
export const PROFILE_IMPORT_REQUESTED = 'PROFILE_IMPORT_REQUESTED';
export const PROFILE_IMPORT_SELECTED = 'PROFILE_IMPORT_SELECTED';
export const PROFILE_IMPORT_COMPLETED = 'PROFILE_IMPORT_COMPLETED';
export const PROFILE_EXPORT_REQUESTED = 'PROFILE_EXPORT_REQUESTED';
export const PROFILE_EXPORT_CONFIRMED = 'PROFILE_EXPORT_CONFIRMED';
export const PROFILE_EXPORT_READY = 'PROFILE_EXPORT_READY';
export const PROFILE_TRANSFER_FAILED = 'PROFILE_TRANSFER_FAILED';
// Emitted when additional ghosts become available
export const GHOST_UNLOCKED = 'GHOST_UNLOCKED';
// Emoji drum layout updated for a ghost
export const DRUM_LAYOUT_UPDATED = 'DRUM_LAYOUT_UPDATED';
// Reminder and overlay flow for emoji reactions
export const REACTION_REMINDER_READY = 'REACTION_REMINDER_READY';
export const REACTION_OVERLAY_REQUESTED = 'REACTION_OVERLAY_REQUESTED';
export const REACTION_SELECTED = 'REACTION_SELECTED';
export const REACTION_FINALE_STATE_UPDATED = 'REACTION_FINALE_STATE_UPDATED';
export const REACTION_FINALE_RECALCULATE_REQUESTED = 'REACTION_FINALE_RECALCULATE_REQUESTED';
// Unified notification whenever dialog awaits user input
export const DIALOG_AWAITING_INPUT_CHANGED = 'DIALOG_AWAITING_INPUT_CHANGED';
// Control-panel scroll events
export const CHAT_SCROLL_UP = 'CHAT_SCROLL_UP';
export const CHAT_SCROLL_DOWN = 'CHAT_SCROLL_DOWN';
export const CHAT_LOAD_OLDER = 'CHAT_LOAD_OLDER';
export const STATUS_SHOW = 'STATUS_SHOW';
// Overlay for quest items is ready to render
export const QUEST_ITEM_OVERLAY_READY = 'QUEST_ITEM_OVERLAY_READY';
// Generic modal control events
export const MODAL_SHOW = 'MODAL_SHOW';
export const MODAL_HIDE = 'MODAL_HIDE';
// Request to display an overlay from canvas or data URL
export const OVERLAY_SHOW = 'OVERLAY_SHOW';
// Request to open media in lightbox
export const MEDIA_OPEN = 'MEDIA_OPEN';
// User profile including avatar has been saved
export const USER_PROFILE_SAVED = 'USER_PROFILE_SAVED';

export const ALL_EVENTS = Object.freeze([
  DUALITY_STARTED,
  EVENT_STARTED,
  EVENT_MESSAGE_READY,
  QUEST_STARTED,
  QUEST_READY,
  QUEST_COMPLETED,
  EVENT_COMPLETED,
  DUALITY_STAGE_STARTED,
  DUALITY_COMPLETED,
  DETECTION_SEARCH,
  DETECTION_DONE_EVENT,
  DETECTION_STOPPED,
  BUTTON_STATE_UPDATED,
  BUTTON_VISIBILITY_UPDATED,
  EFFECT_UPDATE_REQUESTED,
  EFFECT_STYLE_UPDATED,
  EFFECT_DEFAULTS_SAVED,
  VIEW_RENDER_REQUESTED,
  VIEW_CAMERA_RENDER_REQUESTED,
  MESSENGER_POSTS_READY,
  REGISTRATION_NAME_CHANGED,
  GEO_STATUS_UPDATED,
  CAMERA_PREVIEW_READY,
  CAMERA_PREVIEW_CLEARED,
  APP_RESET_REQUESTED,
  APP_RESET_COMPLETED,
  PROFILE_IMPORT_REQUESTED,
  PROFILE_IMPORT_SELECTED,
  PROFILE_IMPORT_COMPLETED,
  PROFILE_EXPORT_REQUESTED,
  PROFILE_EXPORT_CONFIRMED,
  PROFILE_EXPORT_READY,
  PROFILE_TRANSFER_FAILED,
  DIALOG_AWAITING_INPUT_CHANGED,
  DIALOG_WIDGET_READY,
  DIALOG_CLEAR,
  GHOST_UNLOCKED,
  DRUM_LAYOUT_UPDATED,
  REACTION_REMINDER_READY,
  REACTION_OVERLAY_REQUESTED,
  REACTION_SELECTED,
  REACTION_FINALE_STATE_UPDATED,
  REACTION_FINALE_RECALCULATE_REQUESTED,
  CHAT_SCROLL_UP,
  CHAT_SCROLL_DOWN,
  CHAT_LOAD_OLDER,
  STATUS_SHOW,
  QUEST_ITEM_OVERLAY_READY,
  MODAL_SHOW,
  MODAL_HIDE,
  OVERLAY_SHOW,
  MEDIA_OPEN,
  USER_PROFILE_SAVED
]);
