import { resolveAssetUrl } from '../assetsBaseUrl.js';

const NODE_ARTIFACT_BASE = 'images/artifacts/nectosphere_node_1';
const OVERLAY_LAYOUT = {
  canvasWidth: 1536,
  canvasHeight: 1024,
  x: 0,
  y: 0,
  width: 1536,
  height: 512
};

const buildOverlay = artifact => ({
  ...OVERLAY_LAYOUT,
  collage: false,
  background: {
    src: resolveAssetUrl(`${NODE_ARTIFACT_BASE}/${artifact}`)
  }
});

const buildQuest = (id, target, artifact) => ({
  id,
  type: 'camera',
  requirement: { type: 'object', target },
  overlay: buildOverlay(artifact)
});

const buildAutoReply = targetEmoji => ({
  author: 'user',
  autoGenerated: { targetEmoji }
});

export default {
  id: 'guest1',
  displayName: '🌙 ⏸️ 💀',
  avatar: resolveAssetUrl(`${NODE_ARTIFACT_BASE}/artifact_nectosphere_node.webp`),
  reactions: {
    'guest1-handshake': ['🙈'],
    'guest1-bed': ['🙈'],
    'guest1-bottle': ['🙈'],
    'guest1-chair': ['🙈'],
    'guest1-clock': ['🙈']
  },
  sounds: {
    message: {
      ghost: resolveAssetUrl('audio/ghost_effect.mp3'),
      user: resolveAssetUrl('audio/type_sound.mp3')
    },
    detection: resolveAssetUrl('audio/ghost_effect.mp3')
  },
  stages: [
    {
      id: 'guest1-handshake',
      reactions: ['🙈'],
      reactionPreset: '🙈',
      event: {
        id: 'handshake',
        autoStart: true,
        messages: [
          { author: 'user', text: 'guest1.handshake.user1' },
          { author: 'ghost', text: 'guest1.handshake.ghost1' },
          { author: 'user', text: 'guest1.handshake.user2' },
          { author: 'ghost', text: 'guest1.handshake.ghost2' },
          { author: 'ghost', text: 'guest1.request.teddy' }
        ]
      },
      quest: buildQuest('find-teddy-bear', 'teddy bear', 'artifact_1.webp')
    },
    {
      id: 'guest1-bed',
      reactions: ['🙈'],
      reactionPreset: '🙈',
      event: {
        id: 'bed',
        autoStart: true,
        messages: [
          { author: 'ghost', text: 'guest1.request.bed' },
          buildAutoReply('🛏')
        ]
      },
      quest: buildQuest('find-bed', 'bed', 'artifact_2.webp')
    },
    {
      id: 'guest1-bottle',
      reactions: ['🙈'],
      reactionPreset: '🙈',
      event: {
        id: 'bottle',
        autoStart: true,
        messages: [
          { author: 'ghost', text: 'guest1.request.bottle' },
          buildAutoReply('🍼')
        ]
      },
      quest: buildQuest('find-bottle', 'bottle', 'artifact_3.webp')
    },
    {
      id: 'guest1-chair',
      reactions: ['🙈'],
      reactionPreset: '🙈',
      event: {
        id: 'chair',
        autoStart: true,
        messages: [
          { author: 'ghost', text: 'guest1.request.chair' },
          buildAutoReply('🪑')
        ]
      },
      quest: buildQuest('find-chair', 'chair', 'artifact_4.webp')
    },
    {
      id: 'guest1-clock',
      reactions: ['🙈'],
      reactionPreset: '🙈',
      event: {
        id: 'clock',
        autoStart: true,
        messages: [
          { author: 'ghost', text: 'guest1.request.clock' },
          buildAutoReply('🕒')
        ]
      },
      quest: buildQuest('find-clock', 'clock', 'artifact_5.webp')
    },
    {
      id: 'guest1-finale',
      event: {
        id: 'finale',
        autoStart: true,
        messages: [
          { author: 'ghost', text: 'guest1.finale.song', effects: { reactionFinale: true } },
          {
            author: 'ghost',
            type: 'youtube',
            youtubeUrl: 'https://youtu.be/sw63yEVj4AM',
            text: 'guest1.finale.video'
          },
          { author: 'ghost', text: 'guest1.finale.goodbye' }
        ]
      }
    }
  ],
  unlock: { requires: ['guide'], alwaysVisible: true },
  messenger: {
    post: [{ type: 'always' }],
    'switch-ghost': [{ type: 'always' }],
    'toggle-camera': [{ type: 'localAuthReady' }, { type: 'aiReady' }],
    'reset-data': [{ type: 'always' }],
    'scroll-up': [{ type: 'always' }],
    'scroll-down': [{ type: 'always' }]
  }
};
